name = "backend"
compatibility_date = "2024-09-10"

 [vars]
 DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2E2NjFiNTAtNDkzMS00OGQzLWJjZjAtMjI4Y2U2N2NmYTdiIiwidGVuYW50X2lkIjoiY2E1Y2JlZWIzYWE3NTliZGYwZGIwNWJlOTg4OWUxMTMzN2RhMDA1MWY5ODc2NTViYjYwYWI0YzVjYTEzZWQxYyIsImludGVybmFsX3NlY3JldCI6IjM0M2UzYWY1LTMxZGUtNDkwYy04MDRlLTA3NjIxZmExNzAyZiJ9.n4MIAp_YU2BWda1aW-VZN0kqXOgknA_j2Dk_n3bbIb0"

JWT_SECRET= "jw-secrewrwerwe"